In [34]:
# Import the necessary packages
import numpy as np 
import pandas as pd 
from sklearn import datasets, metrics
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Lasso
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.linear_model import ElasticNet
import warnings

# Load the dataset

digits = datasets.load_breast_cancer()

In [35]:
# Create feature and target arrays
X = digits.data
y = digits.target

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [36]:
# Logistic Regression model

clf = LogisticRegression()

In [37]:
# fit the training data with the model

clf.fit(X_train, y_train)

C:\Users\5021259\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [38]:
# Prediction the Y from the X_test

clf.predict(X_test)

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1])

In [39]:
# Repeat the same steps except with L2 Regularization (Lasso)

clf2 = Lasso(fit_intercept=True, alpha=0.1)
clf2.fit(X_train, y_train)

Lasso(alpha=0.1)

In [40]:
Result = clf2.predict(X_test)
print(np.mean((y_test - Result) ** 2))
r2_score(y_test, Result)

0.06024858164914945


0.741074547912584

In [41]:
clf2.predict(X_test)

array([-0.01450961,  0.63336618,  0.69640961,  0.76682997,  0.93477106,
        0.90732737,  0.82991731,  0.07172038,  0.11868962,  0.48835615,
       -0.04338813,  0.2400181 ,  0.2973081 ,  0.60824355,  1.02904469,
        0.4306182 ,  0.79120585,  0.81849669,  0.69840833,  0.7985301 ,
        0.79441793,  0.77152861,  1.12081183,  1.12928413,  0.06666825,
        0.2245542 ,  0.41409551, -0.04218798,  0.37401991,  0.3252612 ,
        1.05624649,  0.83871501,  0.83062151,  0.97913757,  0.87469989,
        0.9689425 ,  0.84314495,  0.8345907 ,  0.02614133,  0.57129418,
        0.67318042,  0.80110117,  0.82199175,  0.35873694,  0.95241238,
        0.96153788,  0.70350211,  1.01083571,  0.82588238,  1.22690759,
       -0.31650171,  0.66072571,  0.75966621,  0.9522941 ,  0.01476788,
        0.50854212,  0.59392211,  1.00188422,  0.05618182,  0.32307906,
        0.31810225,  0.12901034,  0.63667754,  0.37619031,  0.34086957,
        0.95174424,  0.35880209,  0.92182332, -0.02771301,  0.91

In [42]:
#Repeat the same steps except with Elastic Net Regularization

regr = ElasticNet(random_state=0)
regr.fit(X_train, y_train)
clf2.predict(X_test)

array([-0.01450961,  0.63336618,  0.69640961,  0.76682997,  0.93477106,
        0.90732737,  0.82991731,  0.07172038,  0.11868962,  0.48835615,
       -0.04338813,  0.2400181 ,  0.2973081 ,  0.60824355,  1.02904469,
        0.4306182 ,  0.79120585,  0.81849669,  0.69840833,  0.7985301 ,
        0.79441793,  0.77152861,  1.12081183,  1.12928413,  0.06666825,
        0.2245542 ,  0.41409551, -0.04218798,  0.37401991,  0.3252612 ,
        1.05624649,  0.83871501,  0.83062151,  0.97913757,  0.87469989,
        0.9689425 ,  0.84314495,  0.8345907 ,  0.02614133,  0.57129418,
        0.67318042,  0.80110117,  0.82199175,  0.35873694,  0.95241238,
        0.96153788,  0.70350211,  1.01083571,  0.82588238,  1.22690759,
       -0.31650171,  0.66072571,  0.75966621,  0.9522941 ,  0.01476788,
        0.50854212,  0.59392211,  1.00188422,  0.05618182,  0.32307906,
        0.31810225,  0.12901034,  0.63667754,  0.37619031,  0.34086957,
        0.95174424,  0.35880209,  0.92182332, -0.02771301,  0.91